codelingo/codelingo

commands/docs.go

Use github.com/pkg/browser to open the docs
in the user's default browser. Should work
on Linux, Windows and OS X.
Fixes #7

commands: open docs in default browser

---

tenet/driver/binary/service.go

This relies on a change in the tenets package that I will be filing shortly, however this code is what made it start running properly for me on my OS X machine.

Make the binary driver use tcp connections on OS X. Fixes #20

---

commands/docs.go
commands/write_doc.go

"lingo docs" will now render the tenet docs
to HTML. Because the content comes from tenets,
and tenets could come from anywhere, we sanitise
the HTML output before presenting to the user.
Also changed "writeTenetDoc" to return errors,
logging in the "writeDoc" top-level command
function. In doing this, I found a data race:
multiple goroutines writing to the same map.
I've changed them to write to pre-sized slice
elements.
Fixes #23

Render tenet docs to HTML

---

commands/review/confirm.go
tenet/driver/remote/service.go

Whether an issue is inside the diff context is calculated in the tenet. Remove
legacy code which calculated it in the client.

command: Remove diff logic

---

tenets/cacophony/default/no-fmt-print/.lingo
tenets/west/default/allocation/.lingo
tenets/west/default/shadowing/.lingo

Updates variable syntax outside the tenetes/codelingo directory, which was missed in https://github.com/codelingo/codelingo/pull/58

Update non codelingo variables.

---

Gopkg.lock
flows/codelingo/docs/main.go
flows/codelingo/pull-request/main.go
flows/codelingo/review/main.go
flows/codelingo/review/review.txt
flows/codelingo/review/review/checksyntax.go
flows/codelingo/review/review/confirm.go
flows/codelingo/review/review/review.go
flows/codelingo/review/review/review_test.go
flows/codelingo/review/review/reviewpr.go
flows/codelingo/rewrite/main.go
flows/codelingo/rewrite/rewrite/codemod.go
flows/codelingo/rewrite/rewrite/confirm.go
flows/codelingo/rewrite/rewrite/review.go
flows/codelingo/rewrite/rewrite/writer.go
flows/codelingo/search/main.go

Remove hardcoded Flow endpoints from the lingo client into this repo. An
`install flow` command will be added to the client to install the given Flow
cli endpoint.

Move Flow SRC from codelingo/lingo repo

---

tenets/codelingo/php/sql-concats/ideal-solution.lingo

Rewrite SQL injection tenet. 
Replace the magic features - `edge` is implemented, and `path` is well specced out.
Flesh out the details - it will actually work (with some specified caveats) one `path` syntax, and `"reaches"` and `"defines"` weave endpoints on the PHP lexicon are implemented.

Update ideal SQL injection tenet

---

tenets/codelingo/go/lingo_bundle.yaml
tenets/codelingo/go/todo/README.md
tenets/codelingo/go/todo/codelingo.yaml
tenets/codelingo/go/todo/example.go

Keep the TODO tenet, but remove it from the Go bundle so that it still works for files that import it.
Add tenets in the bundle directory, but not in the bundle yaml.

Fix go bundle

---

tenets/codelingo/go/unsafe-go-routine-variables/codelingo.yaml
tenets/codelingo/go/unsafe-go-routine-variables/expected.json
tenets/codelingo/go/unsafe-go-routine-variables/test.go

Move tenet from the platform to this repo, as it applies generally.
Add variable name to the comment so the user can quickly identify the bug.
Currently gets false positives for the `close` ident, since we can't easily distinguish variable declarations from other identifiers. This can be solved by changing the meaning of `type` to assert that the `type` property exists https://trello.com/c/zPq9NzOt/453-has-property-assertion.

Move unsafe go routine tenet from platform.

---

registry/tenets.yaml
tenets/codelingo/code-review-comments/avoid-renaming-imports/codelingo.yaml
tenets/codelingo/code-review-comments/avoid-renaming-imports/example2.go
tenets/codelingo/code-review-comments/avoid-renaming-imports/expected.json
tenets/codelingo/code-review-comments/avoid-renaming-imports/issues.yaml

If there is a renamed import, assert that there is no other import with the same ending, rather than asserting that there is an import without the same ending. Make sure the two import statements are not the same.

Fix avoid-renaming-imports.

---

tenets/codelingo/effective-go/comment-first-word-as-subject/codelingo.yaml
tenets/codelingo/effective-go/comment-first-word-when-empty/codelingo.yaml
tenets/codelingo/effective-go/comment-first-word-when-empty/example.go
tenets/codelingo/effective-go/comment-first-word-when-empty/expected.json

Though these two tenets address the same rule they are used in a different way, and you can't import two tenets in the same codelingo.yaml file separately. The `comment-first-word-as-subject` tenet is mature, and produces reasonably good rewrite output on a first pass and the `comment-first-word-when-empty` tenet is going to be more useful interactively.

Move empty function comment to its own tenet.

---

tenets/codelingo/modica/null-check/codelingo.yaml

Now the php.file fact won't match every node in the repository, it'll just match files that sit inside a directory in the directory tree.
This is untested (as all clusters were down when I wrote it), and may have off by one issues relating to directories etc. Also, it may not actually speed up queries because of all the extra dgraph queries required.

Optimise file searching with path.

---

tenets/codelingo/code-review-comments/context-first-arg/codelingo.yaml
tenets/codelingo/code-review-comments/context-first-arg/example.go

Was getting false positives from contexts in other structures. This should fix it

Fix context-first-arg tenet to only look at field lists related to functions

---

tenets/codelingo/effective-go/underscores-in-name/codelingo.yaml

Ignore names that have a length of one to eliminate false positives from blank identifiers. Will update this tenet with a new expected.json file and additional test cases ASAP

Fix blank identifier false positive

---

flows/codelingo/rewrite/rewrite/writer.go
flows/codelingo/rewrite/rewrite/writer_test.go

Added "original" line data to the comment struct so it can be used when automating rewrite PR comments. This will save having to recalculate diff positions and extract the line data from the diff. Also fixed capitalisation on comment test structs as all tests were failing on this.
The last couple of tests are still failing in writer_test.go (the ones with `Line: 3`). Not sure why but they were failing before I touched the code. We should go back and get those passing.

Add original file line to comment dump and fix (most) tests

---

tenets/codelingo/effective-go/comment-first-word-as-subject/codelingo.yaml
tenets/codelingo/effective-go/comment-first-word-as-subject/example_test.go
tenets/codelingo/effective-go/comment-first-word-as-subject/expected.json

Users typically don't care about conventional comments on test functions. Nor does godoc, in fact.

Exclude tests from comment-first-word-as-subject.

---

tenets/codelingo/code-review-comments/do-not-discard-errors/README.md
tenets/codelingo/code-review-comments/do-not-discard-errors/codelingo.yaml
tenets/codelingo/code-review-comments/do-not-discard-errors/example.go
tenets/codelingo/code-review-comments/do-not-discard-errors/issues.yaml
tenets/codelingo/code-review-comments/return-discarded-errors/README.md
tenets/codelingo/code-review-comments/return-discarded-errors/codelingo.yaml
tenets/codelingo/code-review-comments/return-discarded-errors/example.go

Add a tenet that returns all discarded errors. Current rewrite returns a new set of arguments but doesn't ensure that error is assigned to, as that would require multiple rewrite decorators which is involved due to changing offsets. It also has to be run through gofmt after the rewrite.

Return discarded errors

---

registry/tenets.yaml
tenets/codelingo/psr2/lingo_bundle.yaml
tenets/codelingo/psr2/lower-case-constant-values/.codelingoignore
tenets/codelingo/psr2/lower-case-constant-values/README.md
tenets/codelingo/psr2/lower-case-constant-values/codelingo.yaml
tenets/codelingo/psr2/lower-case-constant-values/example-orig.php
tenets/codelingo/psr2/lower-case-constant-values/expected.json
tenets/codelingo/psr2/lower-case-constant-values/orig.php

From PSR2:
PHP keywords MUST be in lower case.
The PHP constants true, false, and null MUST be in lower case.

Add PSR2 tenet to find and fix non-lowercase language constants

---

registry/tenets.yaml
tenets/codelingo/mozillazg-go-cos/always-close-object-response-body/codelingo.yaml
tenets/codelingo/mozillazg-go-cos/always-close-object-response-body/expected.json
tenets/codelingo/mozillazg-go-cos/always-close-object-response-body/lingo_bundle.yaml
tenets/codelingo/mozillazg-go-cos/always-close-object-response-body/main.go

This will match most of the Object methods that return responses. There's a couple of methods not caught as they have the response in a different position in the returns field list.

Add tenet to ensure responses are closed for go-cos Object struct

---

tenets/codelingo/code-review-comments/return-discarded-errors/codelingo.yaml

Remove undefined variable.
Move decorator to error assignment.

Fix return-discarded-errors tenet's review

---

tenets/codelingo/effective-go/underscores-in-name/codelingo.yaml
tenets/codelingo/effective-go/underscores-in-name/example.go

Make exception for underscores surrounded by digits like `HashSHA512_384`. Discovered in the wild [here](https://github.com/thrasher-/gocryptotrader/pull/315/files#r294140233).

Underscore exception

---

registry/tenets.yaml
tenets/codelingo/go/break-select-in-for/codelingo.yaml
tenets/codelingo/go/break-select-in-for/example.go
tenets/codelingo/go/lingo_bundle.yaml

`example.go` is heavily commented and should explain the issue in detail.

Tenet for breaking a select in a for loop.

---

tenets/codelingo/go/break-select-in-for/codelingo.yaml

Prevents matching on 'continue' etc

exclude other branch stmts

---

registry/tenets.yaml
tenets/codelingo/go/lingo_bundle.yaml
tenets/codelingo/go/pass-struct-by-pointer/codelingo.yaml
tenets/codelingo/go/pass-struct-by-pointer/example.go
tenets/codelingo/go/pass-struct-by-pointer/expected.json

This Tenet/Standard/Spec catches situations where a function is accessing a struct type with exported fields by reference. This can lead to multiple functions, possibly operating on different go-routines, to make read and writes to the same memory at the same time and is generally an anti-pattern.

Add tenet and update registry

---

registry/tenets.yaml
tenets/codelingo/go/lingo_bundle.yaml
tenets/codelingo/go/non-exiting-goroutine/codelingo.yaml
tenets/codelingo/go/non-exiting-goroutine/example.go
tenets/codelingo/go/non-exiting-goroutine/expected.json
tenets/codelingo/go/non-exiting-goroutine/issues.yaml

Add tenet that catches goroutines that are guaranteed not to exit.
Is known to miss issues where a we interpret a break statement that applies to a child for loop or select statement as applying to the parent for loop due to https://github.com/codelingo/codelingo/issues/457.

Add non-exiting-goroutine tenet.

---

tenets/codelingo/go/non-exiting-goroutine/codelingo.yaml
tenets/codelingo/go/non-exiting-goroutine/example.go
tenets/codelingo/go/non-exiting-goroutine/expected.json

We interpreted a break statement that applies to a child for loop or select statement as applying to the parent for loop. This meant we wrongly believed that a goroutine could be exited.
Possible since https://github.com/codelingo/codelingo/issues/457 was fixed.

Fix false negative bug.

---

registry/tenets.yaml
tenets/codelingo/go/lingo_bundle.yaml

Prevent not working tenets which rely on callgraph from being imported in the go bundle

Remove-callgraph-tenets

---

registry/tenets.yaml
tenets/codelingo/go/lingo_bundle.yaml
tenets/codelingo/go/pointer-leaves-method/codelingo.yaml
tenets/codelingo/go/pointer-leaves-method/expected.json
tenets/codelingo/go/pointer-leaves-method/main.go
tenets/codelingo/go/pointer-leaves-method/race/race.go

Catches cases where a method returns a struct containing the receiver pointer. Can lead to data races. You can see the results of the right way and the wrong way by switching out NewUnsafeFirster() for NewSafeFirster() in race.Race() and then running main.go

Add pointer-leaves-method tenet

---

registry/tenets.yaml
tenets/codelingo/go/lingo_bundle.yaml
tenets/codelingo/go/shadowed-variable/codelingo.yaml
tenets/codelingo/go/shadowed-variable/examples.go
tenets/codelingo/go/shadowed-variable/expected.json

This spec/tenant is able to detect when a variable is being shadowed.

Add spec to catch shadowed variables

---

registry/tenets.yaml
tenets/codelingo/go/lingo_bundle.yaml
tenets/codelingo/go/reassigned-error/codelingo.yaml
tenets/codelingo/go/reassigned-error/example.go
tenets/codelingo/go/reassigned-error/expected.json

This spec detects when an error isn't being checked before reassignment.

reassigned error spec added

---

registry/tenets.yaml
tenets/codelingo/go/check-reader-bytes-before-err/codelingo.yaml
tenets/codelingo/go/check-reader-bytes-before-err/example.go
tenets/codelingo/go/check-reader-bytes-before-err/expected.json
tenets/codelingo/go/lingo_bundle.yaml

This spec/tenant ensures that io.Reader bytes is processed before checking err

Add spec to ensure Reader bytes is checked before err

---

tenets/codelingo/go/shadowed-variable/codelingo.yaml
tenets/codelingo/go/shadowed-variable/examples.go

Had a lot of false positives showing that the "err" variable was being shadowed, which wasn't true so made the spec ignore "err" variables, and also ignore the "_" variable as it is just a placeholder variable.

Improve shadow variable spec

---

tenets/codelingo/go/reassigned-error/codelingo.yaml

Fixes the false positives caught by the spec: 
(1) when an error is checked by passing it to another function. 
(2) when an if statement contains more than one boolean expression.

Updated reassigned error to catch wider cases

---

.gitignore
tenets/codelingo/code-review-comments/camel-case-constants/codelingo.yaml
tenets/codelingo/code-review-comments/camel-case-constants/expected.json
tenets/codelingo/effective-go/comment-first-word-as-subject/codelingo.yaml
tenets/codelingo/effective-go/comment-first-word-when-empty/codelingo.yaml
tenets/codelingo/effective-go/comment-first-word-when-empty/expected.json
tenets/codelingo/effective-go/update-comment-first-word-as-subject/codelingo.yaml
tenets/codelingo/go/tested/codelingo.yaml
tenets/codelingo/go/tested/expected.json
tenets/codelingo/go/unused-private-functions/codelingo.yaml

golang public/private properties are wrong in many ways:
* strings not bools
* badly named
* like 8% of all our edges in the DB despite being just "is the first letter a capital"
This PR drops all usage of public/private from our specs, in preparation for dropping support for them in platform.

Drop public private

---

registry/tenets.yaml
util/registry/main.go

Make sure every rule in the registry actually exists in the repo.
The reverse is not true yet, since it probably isn't causing any dashboard problems. However, this utility does tell us which rules aren't used, and it wouldn't be that hard to make it generate the registry file.

Create registry consistency checker.

---

README.md

Change badge to point at codelingo/lexiconsdk (was codelingo/lexicon).

Update lexiconsdk badge/url
