commands/review/confirm.go
commands/review/review.go
commands/review/save.go
commands/review/service/reviewboard.go
tenet/dryrun.go
tenet/dryrun_test.go
tenet/issue.go
tenet/tenet.go

Add TenetName, Discard and DiscardReason to issues. This will be used to track
tenet false positives.

Service metrics

---

commands/build.go
commands/common/common.go
commands/pull.go
commands/push.go
tenet/build/binary.go
tenet/build/build.go
tenet/build/docker.go
tenet/driver/base.go
tenet/driver/binary.go
tenet/driver/binary_test.go

Lingo pull now also pulls source code from tenets and builds and installs the
binary.
Move the build code into its own package to be used by both pull and build commands.

Binary Pull

---

tenets/cacophony/default/caught-generic-exceptions/.lingo
tenets/cacophony/default/debug-prints/.lingo
tenets/cacophony/default/no-fmt-print/.lingo
tenets/cacophony/default/raise-generic-exceptions/.lingo
tenets/cacophony/default/redundant-defer-wraps/.lingo
tenets/codelingo/go/bool-param/.lingo
tenets/codelingo/go/empty-slice/.lingo
tenets/codelingo/go/goto/.lingo
tenets/codelingo/go/marshalling/.lingo
tenets/codelingo/go/nil_only_functions/.lingo
tenets/codelingo/go/sprintf/.lingo
tenets/codelingo/php/boolean-argument/.lingo
tenets/codelingo/php/count-in-loop/.lingo
tenets/codelingo/php/empty-catch-block/.lingo
tenets/codelingo/php/offsite-redirection/.lingo
tenets/codelingo/php/sql-concats/ideal-solution.lingo
tenets/modica/default/null-check/.lingo
tenets/west/default/allocation/.lingo
tenets/west/default/shadowing/generated clql

Update args:
```
^([ ]*)([^\t\.\s]*): (".*"|\d*|false|true)$
$1$2 == $3
```
Update variables:
```
^([ ]*)([^\t\.\s]*): \$(.*$)
$1$2 as $3
```

Update CLQL syntax.

---

tenets/codelingo/go/reallocated_slice/broken.go
tenets/codelingo/go/reallocated_slice/codelingo.yaml
tenets/codelingo/go/reallocated_slice/fixed.go

Add tenet for reallocated pointer issue found in Juju.

Reallocated pointer tenet

---

flows/codelingo/review/review/review.go
flows/codelingo/rewrite/rewrite/review.go

Fixes a nil panic when errors occur.

Catch flow errors

---

flows/codelingo/docs/main.go

- Read doc args from doc flow config Don't hardcode arg names. Any args
- specified in flow config are passed through to the template. Default
template expects two args: "title" and "body"

Update Doc Flow

---

flows/codelingo/review/main.go
flows/codelingo/review/review/decorator.go
flows/codelingo/rewrite/rewrite/decorator.go

Remove variable flag and don't dump result to stdout.

Flow Tidy Ups

---

flows/codelingo/rewrite/rewrite/decorator.go
flows/codelingo/rewrite/rewrite/writer.go
flows/codelingo/rewrite/rewrite/writer_test.go
sdk/flow/cli.go

Add a "--new-file" decorator flag and functionality to the Rewrite flow.

Rewrite: New File 

---

tenets/modica/default/transport/codelingo.yaml

ran a migration script on tenets and discovered this

migrate tenet syntax for modica

---

tenets/codelingo/k8/looped_vars_outside_loop/codelingo.yaml
tenets/codelingo/k8/looped_vars_outside_loop/example.go
tenets/codelingo/k8/looped_vars_outside_loop/expected.json

Based off: https://gist.github.com/lavalamp/4bd23295a9f32706a48f

Looped vars outside loop k8 tenet.

---

tenets/codelingo/k8/well-formed-lists/README.md
tenets/codelingo/k8/well-formed-lists/codelingo.yaml
tenets/codelingo/k8/well-formed-lists/example.go
tenets/codelingo/k8/well-named-interface/README.md
tenets/codelingo/k8/well-named-interface/codelingo.yaml
tenets/codelingo/k8/well-named-interface/sync/example.go
tenets/codelingo/k8/well-named-lists/README.md
tenets/codelingo/k8/well-named-lists/codelingo.yaml
tenets/codelingo/k8/well-named-lists/example.go

new k8 tenets: well-formed-lists well-named-interface well-named-lists

---

tenets/codelingo/go/bool-param/codelingo.yaml
tenets/codelingo/go/bool-param/example.go
tenets/codelingo/go/bool-param/expected.json

Add test case and expected.
Specify func name in review comment - to help solve a bug where this tenet comments on the wrong line.

Update bool param tenet.

---

tenets/codelingo/effective-go/avoid-annotations-in-comments/codelingo.yaml
tenets/codelingo/effective-go/avoid-annotations-in-comments/example.go
tenets/codelingo/effective-go/avoid-annotations-in-comments/expected.json

Tenet for https://golang.org/doc/effective_go.html#commentary

Added EG tenet to check for annotations in comments

---

tenets/codelingo/effective-go/comment-first-word-as-subject/README.md
tenets/codelingo/effective-go/comment-first-word-as-subject/codelingo.yaml
tenets/codelingo/effective-go/comment-first-word-as-subject/example.go
tenets/codelingo/effective-go/comment-first-word-as-subject/expected.json

Tenet for https://golang.org/doc/effective_go.html#commentary

Added EG tenet to enforce comment first word is subject

---

tenets/codelingo/effective-go/underscores-in-name/README.md
tenets/codelingo/effective-go/underscores-in-name/codelingo.yaml
tenets/codelingo/effective-go/underscores-in-name/example.go
tenets/codelingo/effective-go/underscores-in-name/expected.json

Tenet for https://golang.org/doc/effective_go.html#mixed-caps

Added EG tenet to check for underscores in names

---

tenets/codelingo/cockroachdb/func-args-inline-comments/README.md
tenets/codelingo/cockroachdb/func-args-inline-comments/codelingo.yaml
tenets/codelingo/cockroachdb/func-args-inline-comments/example.go
tenets/codelingo/cockroachdb/func-args-inline-comments/issues.yaml

Add Cockroach tenet to check for inline comments on func args

---

tenets/codelingo/effective-go/comment-first-word-as-subject/codelingo.yaml

The rewrite is a very simple placeholder for now, but we can improve it as our NLP gets better.

Add comments to uncommented functions.

---

tenets/codelingo/modica/null-check/codelingo.yaml
tenets/codelingo/modica/null-check/expected.json

refer to https://github.com/codelingo/platform/issues/1044

null-check tenet using depth any instead of path.

---

Gopkg.lock

Fixes version errors https://github.com/codelingo/lingo/pull/441

Update lingo version.

---

tenets/codelingo/effective-go/avoid-annotations-in-comments/codelingo.yaml

Regex was picking up things_like_this. Was having issues with some regex syntax not working so gave up and did it this way

Improve tenet to reduce false positives

---

registry/tenets.yaml
tenets/codelingo/psr2/elseif-not-else-if/README.md
tenets/codelingo/psr2/elseif-not-else-if/codelingo.yaml
tenets/codelingo/psr2/elseif-not-else-if/example.php
tenets/codelingo/psr2/elseif-not-else-if/expected.json
tenets/codelingo/psr2/lingo_bundle.yaml

Review flow runs without issue but rewrite does not behave correctly. See comment in codelingo.yaml.

Add PSR2 tenet to check for usage of space-separated else if

---

tenets/codelingo/effective-go/comment-first-word-as-subject/codelingo.yaml
tenets/codelingo/effective-go/comment-first-word-as-subject/example.go
tenets/codelingo/effective-go/comment-first-word-as-subject/expected.json

public == "true" was removed to fix the 'no issues' problem.
This is a test script with many edge-cases.
https://github.com/mullikine/tenets/blob/master/javascript/test-fix-comment.js

Improvements to rewrite for the commit-first-word-as-subject tenet

---

registry/tenets.yaml
tenets/codelingo/effective-go/lingo_bundle.yaml
tenets/codelingo/effective-go/update-comment-first-word-as-subject/README.md
tenets/codelingo/effective-go/update-comment-first-word-as-subject/codelingo.yaml
tenets/codelingo/effective-go/update-comment-first-word-as-subject/example.go
tenets/codelingo/effective-go/update-comment-first-word-as-subject/example_test.go
tenets/codelingo/effective-go/update-comment-first-word-as-subject/expected.json

The new tenet should have fewer false positives.

New tenet update-comment-first-word-as-subject

---

tenets/codelingo/code-review-comments/FULL_TEXT.md
tenets/codelingo/code-review-comments/README.md

This will be annotated with the tenets that enforce each rule. Every tenet in this bundle should have an annotation.

Add full text of Code Review Comments.

---

tenets/codelingo/code-review-comments/do-not-discard-errors/codelingo.yaml
tenets/codelingo/code-review-comments/do-not-discard-errors/example.go
tenets/codelingo/code-review-comments/do-not-discard-errors/expected.json

Catch ignored errors like https://github.com/rfjakob/gocryptfs/pull/331

Do not ignore errors

---

tenets/codelingo/mssola-user_agent/else-if-when-mutually-exclusive/codelingo.yaml
tenets/codelingo/mssola-user_agent/else-if-when-mutually-exclusive/expected.json
tenets/codelingo/mssola-user_agent/else-if-when-mutually-exclusive/main.go

Inspired by this PR comment https://github.com/mssola/user_agent/pull/41/files/edb5c17fc5816d71144ecaa5ea7c2d4ba1cecd52#r153998505

 Add else-if-when-mutually-exclusive tenet

---

tenets/codelingo/cockroachdb/lingo_bundle.yaml
tenets/codelingo/code-review-comments/lingo_bundle.yaml
tenets/codelingo/effective-go/lingo_bundle.yaml
tenets/codelingo/go/lingo_bundle.yaml
tenets/codelingo/lightning-network-daemon/lingo_bundle.yaml
tenets/codelingo/lomik-go-carbon/lingo_bundle.yaml
tenets/codelingo/modica/lingo_bundle.yaml
tenets/codelingo/php/lingo_bundle.yaml

These files are needed to correctly import tenets. Used a script to ensure consistency. Find it at github.com/daanikus/bundlegen

Run script to tidy up all lingo_bundle files

---

Gopkg.lock
sdk/flow/build.sh

Updated CLQL for docs actions. Will fix errors and support both flows and actions.

rebuild docs and remove x86 from build.sh

---

tenets/codelingo/go/ticker-in-for-select/codelingo.yaml

correct yaml comment.

---

tenets/codelingo/go/lingo_bundle.yaml

We weren't able to import codelingo/go

update avoid-delayed-must-calls reference, make alphabetical

---

registry/tenets.yaml
tenets/codelingo/go/counter-not-incremented/codelingo.yaml
tenets/codelingo/go/counter-not-incremented/example.go
tenets/codelingo/go/counter-not-incremented/expected.json
tenets/codelingo/go/lingo_bundle.yaml

Spec from Issue: https://github.com/thrasher-corp/gocryptotrader/pull/355/files
https://trello.com/c/IvQ1W2mn/146-1-implement-spec-infinite-loop

Add counter not incremented spec

---

flows/codelingo/review/review/cli.go

Runs a review direct from e.g. github:
```
$ lingo run review --repo github.com/juju/errors --lingo-file codelingo.yaml --keep-all
Running review flow...
Done! 1 issues found.
```
Exists to support internal use cases; overrides most other flags.

add --repo flag

---

registry/tenets.yaml

Was causing web_backend API to error out

fix rule name in registry

---

Gopkg.lock
registry/tenets.yaml
tenets/codelingo/juju-juju/lingo_bundle.yaml
tenets/codelingo/juju-juju/unmanaged-goroutine-in-worker/codelingo.yaml
tenets/codelingo/juju-juju/unmanaged-goroutine-in-worker/expected.json
tenets/codelingo/juju-juju/unmanaged-goroutine-in-worker/sample.go

It's a little bit loose, in service of readability; could check signatures of Kill and Wait if we wanted but I lean toward not bothering.

unmanaged-goroutine-in-worker rule

---

registry/tenets.yaml
tenets/codelingo/go/lingo_bundle.yaml
tenets/codelingo/go/surprising-for-direction/codelingo.yaml
tenets/codelingo/go/surprising-for-direction/expected.json
tenets/codelingo/go/surprising-for-direction/sample.go

Equivalent to https://lgtm.com/query/rule:1510348425987/lang:go/

surprising-for-direction rule
